# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd561167dddb900ce7e739b73f5c701a0e2e64cdbd7a0f38a023c9c01dcd8872f9d91c0fc2c64b2507c99484cd739a0247ce1cc1a0a27ff18a13a141c84e6822

test:
  secret_key_base: 1059686312b44b2dff845a9114f531f9096483778d973c6f25ddd4fca8017a8af887ec78bac55bdb48d33140fe31a1eae672706c9ce49b772aabbb45645386c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
